<?php
//GROUPS
$name = $this->group['name'];

$this->title = $name;
$this->headTitle(" - $this->title");
$backURL = $this->url(array(
    'controller' => 'groups',
    'action' => 'profile',
    'id'    => $this->group['id']
));
?>

<div id="content">
    <h1 class='participantProfile float-left' id="<?php print $this->group['id']; ?>">
        Add a Meeting of
        <span class=p-name>
            <?php print $this->group['name']; ?>
        </span>
    </h1>
    
    <div class="inline float-right">
        <a href="<?php print $backURL; ?>"> Back to Group Profile</a>
    </div>

    <div id="content-top">
    </div>

    <div id="content-main">
        <form>
        <div class="input-home-wrapper">
            <div class="input-home float-left">
                <?php print $this->dateElement; ?>
            </div>
            
            <div class="input-home float-right">
                <?php print $this->durationElement; ?>
            </div>
        </div>

        <div class="input-home-wrapper attendance-table">
            <?php print $this->meetingTable($this->enrolledList); ?>
        </div>
        
        <div class="input-home-wrapper">
            <div class="input-home float-left">
                <?php print $this->unenrolledElement; ?>
            </div>
            
            <div class="input-home float-right">
                <?php print $this->volunteersElement; ?>
            </div>
        </div>
        
        <div class="input-home-wrapper">
            <?php print $this->notesElement; ?>
        </div>
      </form>
        
        <button class="savebutton" id="saveData">Save</button>  
    </div>
    
</div> <!-- /#content -->

<!-- javascript divs go here -->
