<?php
//GROUPS
$name = $this->group['name'];

$this->title = $name;
$this->headTitle(" - $this->title");
$backURL = $this->url(array(
    'controller' => 'groups',
    'action' => 'list'
));

//Set up header counts
$ptcpCount = count($this->ptcps);
$meetingCount = count($this->meetings);

//Set up URLs

$addMeetingToGroupUrl = $this->url(array(
                               'controller'  =>'groups',
                               'action'      =>'meetings',
                               'id'          => $this->group['id']));

$addPtcpToGroupUrl = $this->url(array(
                               'controller'  =>'groups',
                               'action'      =>'enroll',
                               'type'        =>'ptcp',
                               'id'          => $this->group['id']));

// Set up Meetings Tab
if ($meetingCount == 0) {
    $mtgList = "<h2>This group hasn't had any recorded meetings yet.</h2>";
    $mtgList .= "<button class='float-right' id='addMeeting'>Add Meeting Record</button>";
} else {
    $mtgList = "<div class='groupfilter'></div>";
    $mtgList .= "<button class='float-right' id='addMeeting'>Add Meeting Record</button>";
    $mtgList .= $this->meetingList($this->meetings);
}

$mtgTab = $mtgList;

// Set up Forms Tab
if (count($this->forms) == 0) {
    $formList = "<h2>No forms associated with this group yet.</h2>";
} else {
    $formList = $this->formsTable('forms', $this->forms);
}

$formTab = $formList;

//Set up Participants Tab
if ($ptcpCount == 0) {
    $ptcpList = "<h2>No participants enrolled in this group</h2>";
} else {
    $links = array('profile');
    $ptcpList = '<table class="p-list-table">';
    foreach($this->ptcps as $ptcp) {
        $ptcpList .= $this->tableRow('person','participants',$ptcp,$links);
    }
    $ptcpList .= '</table>';
}

$ptcpAddMore = '<a class="add-link" href=' . $addPtcpToGroupUrl . '>
                            Enroll participants in ' . $this->title . ' 
                        </a>
                ';

$bottomLinks = "<div class='bottom-links'> $ptcpAddMore </div>";

$ptcpTab = $ptcpList . $bottomLinks;

//PASS EVERYTHING TO TABS

$this->tabPane('group', $mtgTab, array('title' => 'Meetings'));
$this->tabPane('group', $ptcpTab, array('title' => 'Participants'));
$this->tabPane('group', $formTab, array('title' => 'Forms'));
?>

<div id="content">
    <div class="float-left">
        <h1 class='participantProfile' id="<?php print $this->group['id']; ?>">
            Group Profile: 
            <span class=p-name>
                <?php print $name; ?>
            </span>
        </h1>
        <dl class="profile-subtitle">
            <dt>Program</dt>
            <dd><a href="#"><?php print $this->progName; ?></a></dd>
        </dl>
    </div>

<div id="dialog-form-edit" class="dialog-form" title="Edit group information">
    <p class="validateTips">Please update values below.</p>
</div>

<div class="inline float-right">
    <a
      id="edit-button"
      data-id="<?php print $this->group['id']; ?>"
      data-type="groups"
      href="#">Edit Group</a>
    <br>
    <a href="<?php print $backURL; ?>"> Back to Group List</a>
</div>

<div id="content-top">
    <!-- <span class="third shaded">
        <strong>Program:</strong> <?php print $this->progName; ?>
    </span>
    
    <span class="third shaded">
        <strong>Participants:</strong> 
            <span id="record-count">
                <?php print $ptcpCount; ?>
            </span>
    </span>
    
    <span class="third shaded">
        <strong>Meetings so far:</strong> <?php print $meetingCount; ?>
    </span> -->
    <dl class="profile-top-attributes">
      <div>
        <dt>Participants</dt>
        <dd><?php print $ptcpCount; ?></dd>
      </div>

      <div>
        <dt>Meetings</dt>
        <dd><?php print $meetingCount; ?></dd>
      </div>
    </dl> 
</div>

<div id="content-main">

    <?php print $this->tabContainer('group'); ?>
    
</div>
    
</div> <!-- /#content -->

<!-- javascript divs go here -->
