<div id="content">

    <h1 class="float-left">Staff</h1>
    <div class="inline float-right">
      Showing <span id="record-count"><?php print $this->count; ?></span> staff records.
    </div>


    <div id="content-top">
        
        <span id="browse" class="float-left">
            <h2>Browse</h2>
        </span>
        
        <span id="searchform"></span>
        
        <?php if ($this->root || $this->mgr) : ?>
        <span id="addNew" class="float-right">
            <button id="addUser">Add New Staff</button>
        </span>
        <?php endif; ?>
        
    </div>

    <div id="content-main">
            <table class="p-list-table">
                <?php 
                    $notMe = FALSE;
                    
                    foreach ($this->list as $user) {
                        $locked = $user['lock'];
                        if ($user['id'] != $this->myID) {
                            $notMe = TRUE;
                        } else {
                            $notMe = FALSE;
                        }

                        $links = array('profile');

                        if (($this->admin) || (!$notMe)) {
                            array_push($links, 'edit');
                        }
                                                
                        if (($this->admin) && ($notMe) && (!$locked)) {
                            array_push($links, 'lock');
                        }
                        
                        if (($this->admin) && ($locked)) {
                            array_push($links, 'unlock');
                            array_push($links, 'archive');
                        }
                        
                        //if(($this->admin) && ($notMe)) {
                        //    array_push($links, 'delete');
                        //} 
                        
                        print $this->tableRow('person', 'users', $user, $links);
                    }

                ?>
            </table>
    
    </div>
    
    <div id="dialog-form" title="Add New Staff">
        <p class="validateTips">
            Please fill out all fields.
        </p>

        <?php if ($this->admin) : ?>
            <p class="hidden" id="admin">.</p>
        <?php endif; ?>

        <?php print $this->form; ?>

    </div>

    <?php if ($this->mgr) : ?>
        <div id="unlock-form" class="dialog-form" title="">
            <p class="validateTips"></p>
            <?php print $this->unlockForm; ?>
        </div>
    <?php endif; ?>
    
        <div id="dialog-form-edit" class="dialog-form" title="Edit user information">
            <p class="validateTips">Please update values below.</p>
        </div>    

   
</div>