<?php
//USERS
$name = $this->user['firstName'] . " " . $this->user['lastName'];
$fName = $this->user['firstName'];

$this->title = $name;
$this->headTitle(" - $this->title");
$backURL = $this->url(array(
    'controller' => 'users',
    'action' => 'list'
));

//Set up header counts
$ptcpCount = count($this->ptcps);

//Set up URLs
$addStaffToProgUrl = $this->url(array(
                               'controller'  =>'users',
                               'action'      =>'associate',
                               'type'        =>'prog',
                               'id'          => $this->user['id']));

$addStafftoPtcpUrl = $this->url(array(
                               'controller'  =>'users',
                               'action'      =>'associate',
                               'type'        =>'ptcp',
                               'id'          => $this->user['id']));

$addStafftoDeptUrl = $this->url(array(
                               'controller'  =>'users',
                               'action'      =>'associate',
                               'type'        =>'dept',
                               'id'          => $this->user['id'])); 


//set up departments tab

if ($this->root || ($this->uid == $this->user['id'])) {
    $privilege = TRUE;
} else {
    $privilege = FALSE;
}

$deptLinks = array('profile');

if ($privilege) {
    array_push($deptLinks,'setHome');
}

$deptTabList = '<table class="p-list-table">';

foreach ($this->depts as $userDept) {
    if (in_array($userDept['id'],$this->homeDepts)) {
        $home = TRUE;
    } else {
        $home = FALSE;
    }
    $deptTabList .= $this->tableRow('entity','depts',$userDept,$deptLinks,$home);
}
$deptTabList .= '</table>';
$deptAddMore = '<div class="bottom-links">
                   <a class="add-link" href=' . $addStafftoDeptUrl . '>
                       Manage departments for ' . $this->title . ' 
                   </a>
                </div>';
$deptTab = $deptTabList . $deptAddMore;



//Set up programs tab
$links = array('profile');
    
if (count($this->programs) == 0) {
    $progList = "<h2>This account is not associated with any program yet.</h2>";
} else {
    $progList = '<table class="p-list-table">';
    foreach ($this->programs as $program) {
        $progList .= $this->tableRow('entity','programs',$program,$links);
    }
    $progList .= '</table>';
}

if ($this->mgr) {
    $progAddMore = '<div class="bottom-links">
               <a class="add-link" href=' . $addStaffToProgUrl . '>
                   Manage ' . $fName . '\'s program enrolment  
               </a>
            </div>';
$progTab = $progList . $progAddMore;
} else {
    $progTab = $progList;
}

//Set up case load tab
$links = array('profile');

if ($ptcpCount == 0) {
    $ptcpList = "<h2>No participants on this caseload yet.</h2>";
} else {
    $ptcpList = $this->ptcpTable('caseload',$this->user['id'], $this->ptcps);
}

$ptcpAddMore = '<a class="add-link" href=' . $addStafftoPtcpUrl . '>
                            Add/remove from ' . $this->user['firstName'] . '\'s caseload  
                        </a>
                ';

$ptcpPurge = '<a class="minus-link" data-ptype="user" data-pid="' . $this->user['id'] . '" id="purge" href="#">
                  Clear "concluded" from caseload. 
              </a>
              ';

$bottomLinks = "<div class='bottom-links'> $ptcpAddMore $ptcpPurge </div>";

$ptcpTab = $ptcpList . $bottomLinks;


// Set up Forms Tab
//if (count($this->forms) == 0) {
//    $formList = "<h2>No forms associated with this program yet.</h2>";
//} else {
//    $formList = $this->formsTable('forms', $this->forms);
//}
//    $formAddMore = '<div class="bottom-links">
//                        <a class="add-link" href=' . $addFormToProgUrl . '>
//                            Add New Form to ' . $this->title . ' 
//                        </a>
//                    </div>';
//if ($this->mgr) {
//    $formTab = $formList . $formAddMore;
//} else {
//    $formTab = $formList;
//}

$formTab = '';




//PASS EVERYTHING TO TABS
$this->tabPane('user',$deptTab,array('title' => 'Departments'));
$this->tabPane('user', $progTab, array('title' => 'Programs'));
$this->tabPane('user', $ptcpTab, array('title' => 'Case Load'));

?>

<div id="content">
  <div class="float-left">
    <h1 class='participantProfile' id="<?php print $this->user['id'];?>">
        Staff Profile:
        <!-- Span class and innerHTML used by unlock.js to print name in dialog box -->
        <span class=p-name>
            <?php print $name; ?>
        </span>
    </h1>
    <dl class="profile-subtitle">
      <dt>Departments</dt>
      <?php
        foreach ($this->depts as $dept) {
      ?>
      <dd><a href="#"><?php print $dept['deptName']; ?></a></dd>
      <?php
        }
      ?>
    </dl>
  </div>
    
<div id="dialog-form-edit" class="dialog-form" title="Edit user information">
    <p class="validateTips">Please update values below.</p>
</div>

<?php if ($this->mgr) : ?>
    <div id="unlock-form" class="dialog-form" title="">
        <p class="validateTips"></p>
        <?php print $this->unlockForm; ?>
    </div>
<?php endif; ?>

<div class="inline float-right">
    <?php
    if (in_array('edit', $this->actions)):
    ?>
    <a
      id="edit-button"
      data-id="<?php print $this->user['id']; ?>"
      data-type="users"
      href="#">Edit</a> |
    <?php
    endif;
    ?>

    <?php
    if (in_array('lock', $this->actions)):
    ?>
    <a
      id="lock-button"
      data-id="<?php print $this->user['id']; ?>"
      data-type="users"
      href="<?php print "/users/lock/id/{$this->user['id']}"; ?>">Lock</a>
    <?php
    endif;
    ?>

    <?php
    if (in_array('unlock', $this->actions)):
    ?>
    <a
      id="unlock-button"
      data-id="<?php print $this->user['id']; ?>"
      data-type="users"
      href="#">Unlock</a> |
    <?php
    endif;
    ?>

    <?php
    if (in_array('archive', $this->actions)):
    ?>
    <a
      id="archive-button"
      data-id="<?php print $this->user['id']; ?>"
      data-type="users"
      href="<?php print "/users/archive/id/{$this->user['id']}"; ?>">Archive</a>
    <?php
    endif;
    ?>
    <br>
    <a href="<?php print $backURL; ?>"> Back to User List</a>
</div>

<div id="content-top">
  <dl class="profile-top-attributes">
    <div>
      <dt>Case Load</dt>
      <dd><?php print $ptcpCount; ?></dd>
    </div>
  </dl>     
    
</div>

<div id="content-main">

    <?php print $this->tabContainer('user'); ?>
    
</div>
    
</div> <!-- /#content -->

<!-- javascript divs go here -->

<div id='dialog-form' title="">
        <?php print $this->statusForm; ?>
    </div>

<div id='dialog-confirm' title="Clear participant records?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"/></span>
        <span id="list">
            The following records will be cleared from your caseload and returned to the program pool:
            <ul id="deleteList">
                
            </ul>
        </span>
    </p>
</div>