<?php
//PROGRAM CALENDAR
$this->title = $this->program['name'];
$this->headTitle(" - $this->title");
$backURL = $this->url(array(
    'controller' => 'programs',
    'action' => 'list'
));
//print_r($this->vJobs);
?>

    <h1 class="float-left">Program Calendar: 
        <?php print $this->title; ?>
    </h1>

    <div class="inline float-right">
        <a href="<?php print $backURL; ?>"> Back to Program List</a>
    </div>

<div id="content-top">
    <span class="third shaded">
        <span class="gamify-profile">
            <span class="topnum"><?php print $this->program['numEvents'];?></span>
            <span class="bottom-desc"><br>events</span>
        </span>
    </span>
    
    <span class="third shaded">
        <span class="gamify-profile">
            <span class="topnum"><?php print $this->program['numVolunteers']; ?></span> 
            <span class="bottom-desc">jobs filled</span>
        </span>
    </span>
    
    <span class="third shaded">
        <span class="gamify-profile">
            <span class="topnum"><?php print $this->program['numNeeded']; ?></span> 
            <span class="bottom-desc">spots to fill</span>
        </span>
    </span>
    
</div>


<div id="content-main">

    <div id="calinfo" class="hidden" data-calType="program" data-calID="<?php print $this->program['id'];?>"></div>
    <div id="programJobs" class="hidden" data-vjobs='<?php echo json_encode($this->vJobs); ?>'></div>
    <div id="readonly" class="hidden" data-readonly="<?php print $this->readOnly; ?>"></div>
    
<div id="prog_scheduler" class="dhx_cal_container" style='width:100%; height:100%;'>
    <div class="dhx_cal_navline">
        <div class="dhx_cal_prev_button">&nbsp;</div>
        <div class="dhx_cal_next_button">&nbsp;</div>
        <div class="dhx_cal_today_button"></div>
        <div class="dhx_cal_date"></div>
        <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
        <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
        <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
    </div>
    <div class="dhx_cal_header"></div>
    <div class="dhx_cal_data"></div>       
</div>

    <div id="dialog-form-enroll" title="Enroll Volunteers">
        <p class="validateTips"></p>
        <?php print $this->enrollVolForm; ?>
        <div id='resource-list' class = 'hidden'>
            <h3>Adding the following volunteers:</h3>
            <hr>
            <div id='resource-list-items'>
                
            </div>
        </div>
    </div>
    
    
</div>