<?php
$this->title = " - Programs";
$this->headTitle($this->title);
?>

<div id="content">

  <h1 class="float-left"> Programs </h1> 
  <div class="inline float-right">
      Showing <span id="record-count"><?php print $this->count; ?></span> program records.
  </div>

  <div id="content-top">
        
        <span id="browse" class="float-left">
            <h2>Browse</h2>
        </span>
        
        <span id="searchform">
            
        </span>
        
     <?php if ($this->mgr) : ?>
        <span id="addNew" class="float-right">
              <button id="addProg">Add New Programs</button>
        </span>
     <?php endif ; ?>
</div>

  <div id="content-main">



    <table id="progs-table" class="p-list-table">
            <?php 
                $links = array('profile');
                if ($this->mgr) {
                    array_push($links, 'edit');
                }
                foreach ($this->programs as $program) {
                    print $this->tableRow('entity', 'programs', $program, $links);
                }
            ?>
    </table>

  <?php if ($this->mgr) : ?>
    <div id="dialog-form" title="Add a Program">
        <p class="validateTips"></p>
        <?php print $this->form; ?>    
    </div>
    
    <div id="dialog-form-edit" class="dialog-form" title="Edit department name">
        <p class="validateTips">Please update values below.</p>
    </div>    
  <?php endif; ?>    
  </div>
</div>
