<?php
$homeOnlySwitch = '<div class="switch-container">
                    <span class="switch-label switch-label-off">Home Only</span>
                    <label class="switch">
                        <input id="home-only-switch" type="checkbox" checked="yes">
                        <span class="slider round"></span>
                    </label>
                    <span class="switch-label switch-label-on">All Departments</span>
                </div>';

$activeOnlySwitch = '<div class="switch-container">
                    <span class="switch-label switch-label-off">Active Only</span>
                    <label class="switch">
                        <input id="active-only-switch" type="checkbox">
                        <span class="slider round"></span>
                    </label>
                    <span class="switch-label switch-label-on">All</span>
                </div>';      
?>


<div id="content">

  <h1 class="float-left"> Participants </h1> 
  <div class="inline float-right">
      Showing <span id="record-count"><?php print $this->count; ?></span> participant records.
  </div>


  <div id="content-top" class="participants">
        
        <span id="browse" class="float-left">
            <h2>Browse</h2>
        </span>
        
        <span id="searchform">
            
        </span>
        
      <span id="table-filters">
        <?php print $homeOnlySwitch ?>
        <?php print $activeOnlySwitch ?>
      </span>
      
        <span id="addNew" class="float-right">
            <button id="addPtcp">Add New Participant</button>
        </span>
        
  </div>

    <div id="content-main">
        <table class="p-list-table">
            <?php
                $links = array('profile', 'edit', 'archive');
                foreach ($this->list as $participant) {
                    $pid = $participant['id'];
                    if (in_array($pid,$this->homeIDs)) {
                        $home = TRUE;
                    } else {
                        $home = FALSE;
                    }
                    print $this->tableRow('person', 'participants', $participant, $links, $home);
                }
            ?>
        </table>
    </div>
        
    <div id="dialog-form" title="Add a New Participant">
        <p class="validateTips">
            Please fill out all fields.
        </p>
        <?php print $this->form; ?>
    </div>
 
    <div id="dialog-form-edit" class="dialog-form" title="Edit participant information">
        <p class="validateTips">Please update values below.</p>
    </div>  
    
    

</div>