<?php
//VOLUNTEER CALENDAR
$this->title = $this->name;
$this->headTitle(" - $this->title");
$backURL = $this->url(array(
    'controller' => 'volunteers',
    'action' => 'profile'
));
//print_r($this->vJobs);
?>

    <h1 class="float-left"> 
        <?php print $this->title; ?>'s Calendar
    </h1>

    <div class="inline float-right">
        <a href="<?php print $backURL; ?>"> Back to Profile</a>
    </div>

<div id="content-top">
    <span class="third">
        
    </span>
    
    <span class="third">
        
    </span>
    
    <span class="third">
        
    </span>
    
</div>


<div id="content-main">

    <div id="calinfo" class="hidden" data-calType="volunteer" 
         data-calMode="<?php print $this->mode;?>" 
         data-calID="<?php print $this->volID;?>">
    </div>    
    
    
<div id="vol_calendar" class="dhx_cal_container" style='width:100%; height:100%;'>
    <div class="dhx_cal_navline">
        <div class="dhx_cal_prev_button">&nbsp;</div>
        <div class="dhx_cal_next_button">&nbsp;</div>
        <div class="dhx_cal_today_button"></div>
        <div class="dhx_cal_date"></div>
        <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
        <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
        <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
    </div>
    <div class="dhx_cal_header"></div>
    <div class="dhx_cal_data"></div>       
</div>

    <div id="dialog-form-enroll" title="Enroll in Event">
        <p class="validateTips"></p>
        <?php print $this->enrollVolForm; ?>
        <div id='resource-list' class = 'hidden'>
            <h3>Adding the following volunteers:</h3>
            <hr>
            <div id='resource-list-items'>
                
            </div>
        </div>
    </div>    
</div>